version: "3.7"
name: "envoy-routing-example"
services:
  server1:
    build:
     context: .
     dockerfile: Dockerfile
    command: ruby -run -ehttpd . -p8001
    ports:
      - 8001:8001
    networks:
      - network1

  server2:
    build:
     context: .
     dockerfile: Dockerfile
    command: ruby -run -ehttpd . -p8002
    ports:
      - 8002:8002
    networks:
      - network1

  envoy:
    image: envoyproxy/envoy:v1.30.1
    volumes:
      - ./envoy.yaml:/envoy.yaml
    ports:
      - 8080:8080
    networks:
      - network1

networks:
  network1:
